-- AlterTable
ALTER TABLE `booking` ADD COLUMN `expiredAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'CHECKED_IN', 'CHECKED_OUT', 'EXPIRED', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'PENDING';
